### ISSUE TITLE
Edit & Delete Functionality - 'Cannot Get/Delete'

### ISSUE THREAD

**Issue by jhan-old** [jaemin-han/hotel-now#3]
I was successfully able to set up users, search query, list data, and transfer data to my 'favorites' page. Two collections, 'favorite' & 'users' also populate correctly. 

I attempted multiple times past two days to set up 'delete' [DELETE] and 'edit' [PUT] functions correctly. However, I've been getting these errors below.

-When I click 'delete' button:
"Cannot DELETE /hotels/favorites/581510864023796751afc84e?_method=DELETE"

-When I click 'Add Comment' link:
"Cannot GET /edit/"

[Database]
<img width="707" alt="db" src="https://cloud.githubusercontent.com/assets/19918594/19832880/e7edf3a8-9dfd-11e6-8b66-8d29ebb53042.png">
[Routes - hotels.js]
<img width="748" alt="hotel route" src="https://cloud.githubusercontent.com/assets/19918594/19832881/eebeadee-9dfd-11e6-9cd6-a4114299aabe.png">
[Views - hotels.ejs]
<img width="947" alt="hotel ejs" src="https://cloud.githubusercontent.com/assets/19918594/19832882/f5db7300-9dfd-11e6-8f8d-f6a4bc1c1022.png">
[Views - favorite.ejs]
<img width="1088" alt="favorites ejs" src="https://cloud.githubusercontent.com/assets/19918594/19832884/fe76c71c-9dfd-11e6-8238-e9074dde7d8b.png">

1) used both render/redirect to make sure it's directing to the correct .ejs files (also verified my models fies)
2) referenced tom-cruise-move-db-rafa-solution and user_auth_itunes files to make sure my files are correct
3) verified/confirmed with two classmates to make sure my setups were correct

Thank you very much!

**Comment by jhan-old** [comment]
@trevorpreston
@gittheking
@jasonseminara
@rapala61
@irwintsay

**Comment by gittheking** [comment]
@jaemin-han, your delete isn't working because you don't have a delete route in your `routes/hotels.js`. 

> "Cannot GET /edit/"

This is happening because your anchor tag on `hotels.ejs` `<a href="/edit/<%= hotels[i]._id %>">Add Comments</a>` isn't rendering the correct url to hit your route, so I would check out the value of `hotels[i]._id` when rendering `hotels.ejs`. You can use chrome's inspect element to see if that link looks correct.

**Comment by trevorpreston** [comment]
@jaemin-han Is this complete?  If so, please close.

**Comment by rapala61** [comment]
Last update: not yet solved but made some progress. Updating in 30 min. @jaemin-han

**Comment by rapala61** [comment]
Hey, any updates here? @jaemin-han

**Comment by jhan-old** [comment]
@rapala61 I got the Delete function to work finally. I am troubleshooting Put function at this moment. I will keep you posted no later than 3pm.

**Comment by rapala61** [comment]
Ok so you are making progress. Ill close this issue since if its open, it means you are blocked. Create a new one later in case that you hit a blocker with that route.
